main:
	gcc -o main source/main.c -lm -lncurses -g
test:
	gcc -o test source/test.c -lm -lncurses -g
gravitas: 
	g++ -o gravitas source/gravitas.cpp -lGL -lGLEW -lGLU -lGL -lglfw -lm -lXrandr -lXi -lXxf86vm -lpthread -g
clean: 
	rm main ; rm test
